Fix for "terraform init" failing (error
"terraform init" fails when trying to create a new ACE Box (Terraform on AWS). That is due to hashicorp/aws version 5.4.0.

Error: "Could not retrieve the list of available versions for provider hashicorp/aws ..."

Update to latest version 5.47.0 fixes this issue ("terraform init" runs through fine without issue above)